version: '3'
services:
  graph-tool:
    build: ./docker
    network_mode: "host"
    ports:
      - "27017:27017"
    volumes:
      - ../twitter_siphon:/code
    command: python3 "/code/__init__.py"
